# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := dns

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

dns: 
	@echo "==== Building dns ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f dns.make

clean:
	@${MAKE} --no-print-directory -C . -f dns.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   dns"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
